services:
#  backend:
#    depends_on:
#    - db

  # https://hub.docker.com/_/postgres/
  db:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"

# Data initialization is done in the SpringBoot startup
#    volumes:
#      # Init script with the default DB's data
#      - './src/main/postgres/:/docker-entrypoint-initdb.d/'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pwd

  adminer:
    image: adminer
    restart: always
    ports:
      - "18080:8080"